name: backend
description: Smarty Entregas Backend (Dart)
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: any
  shelf_router: any
  postgres: any
  shelf_cors_headers: ^0.1.0
  crypto: any
  dotenv: ^4.2.0

dev_dependencies:
  lints: any
